---
title: "ST309_Project"
author: "Paxton Quek, Patricia Yin"
date: "02/02/2021"
output: pdf_document
---

##  Text Analysis
```{r}
library(tidyverse)
library(car)
library(ggplot2)
library(readxl)
library(dplyr)
library(tidytext)
library(wordcloud2)
data(stop_words)



listings_text <- read_excel("9Dec2019_DescriptorText.xlsx")



# Analysis for "Summary"
text1 <- pull(listings_text,summary)
text1_df = data_frame(text1)
text1_tidy = text1_df %>% unnest_tokens(word1, text1)

# grouped
text1_tidypiped = text1_df %>% unnest_tokens(word1, text1) %>% count(word1, sort=T)

# remove stop-words; by required due to different variable names word1 and word
text1_noS <- anti_join(text1_tidy, stop_words, by=c("word1" = "word"))
# pipe the words
text1_noS_piped = text1_noS %>% count(word1, sort=T) %>% filter(n>250)
text1_noS_piped %>% wordcloud2



# Analysis for "Description"
text2 <- pull(listings_text,description)
text2_df = data_frame(text2)
text2_tidy = text2_df %>% unnest_tokens(word2, text2)

# grouped
text2_tidypiped = text2_df %>% unnest_tokens(word2, text2) %>% count(word2, sort=T)

# remove stop-words; by required due to different variable names word1 and word
text2_noS <- anti_join(text2_tidy, stop_words, by=c("word2" = "word"))
# pipe the words
text2_noS_piped = text2_noS %>% count(word2, sort=T) %>% filter(n>250)
text2_noS_piped %>% wordcloud2



# Analysis for "Space"
text3 <- pull(listings_text,description)
text3_df = data_frame(text3)
text3_tidy = text3_df %>% unnest_tokens(word3, text3)

# grouped
text3_tidypiped = text3_df %>% unnest_tokens(word3, text3) %>% count(word3, sort=T)

# remove stop-words; by required due to different variable names word1 and word
text3_noS <- anti_join(text3_tidy, stop_words, by=c("word3" = "word"))
# pipe the words
text3_noS_piped = text3_noS %>% count(word3, sort=T) %>% filter(n>250)
text3_noS_piped %>% wordcloud2